export const STUDIO_COPY = Object.freeze({
  brand: 'Cosmetique AI',
  eyebrow: 'Extraction produit',
  title: 'Le produit, isolé proprement.',
  intro: 'Importez une photo, vérifiez le masque réel et arrêtez-vous sur le détourage transparent.',
  privateWorkspace: 'Espace privé',
  campaignHistory: 'Retour au tableau de bord',
  source: {
    title: 'Importez la vraie photo produit',
    description: 'La photo est enregistrée avant l’extraction. Le serveur renvoie ensuite le masque et le détourage réels.',
    upload: 'Choisir une photo',
    change: 'Changer la photo',
    remove: 'Retirer la photo',
    stored: 'Source enregistrée',
    waiting: 'En attente de la source',
    ready: 'Prête à être enregistrée',
    name: 'Nom du produit',
    brand: 'Marque',
    optional: 'Facultatif',
    category: 'Catégorie',
    file: 'Fichier',
    storage: 'Stockage',
    privateStorage: 'Stockage privé',
    notStored: 'Pas encore enregistrée',
    createLock: 'Extraire le produit',
    refreshLock: 'Relancer l’extraction',
    creatingLock: 'Extraction en cours…',
    emptyTitle: 'Déposez une photo produit',
    emptyHelp: 'JPG, PNG ou WebP, 10 Mo maximum.',
    helper: 'Aucun décor ni fournisseur externe n’est lancé depuis cette étape.',
  },
  lock: {
    title: 'Vérifiez ce qui reste dans l’image',
    description: 'Le masque et le détourage sont les seuls résultats présentés par ce test.',
    statusReview: 'À vérifier',
    statusValidated: 'Validé',
    statusRejected: 'Refusé',
    candidate: 'Candidat',
    confidence: 'Confiance',
    revision: 'Révision',
    select: 'Sélectionner',
    positive: 'Garder',
    negative: 'Retirer',
    pan: 'Déplacer',
    mask: 'Afficher le masque',
    save: 'Enregistrer les corrections',
    saving: 'Enregistrement',
    validate: 'Valider l’extraction',
    reject: 'Envoyer en revue',
    correctionReason: 'Motif de revue',
    correctionPlaceholder: 'Expliquez ce qui doit être vérifié.',
    evidence: 'Preuves du verrouillage',
    source: 'Source',
    maskArtifact: 'Masque',
    cutout: 'Détourage',
    models: 'Modèles',
    noArtifact: 'Non disponible',
    noCandidates: 'Aucun candidat supplémentaire n’est disponible.',
    reviewNote: 'Un contour ambigu, une main ou un objet supplémentaire doit être corrigé avant de valider.',
  },
  engine: {
    title: 'État de l’extraction',
    ready: 'Runtime prêt',
    unavailable: 'Runtime indisponible',
    degraded: 'Runtime en mode dégradé',
    checking: 'Vérification du runtime',
    unavailableHelp: 'Le studio attend un runtime d’extraction confirmé. Aucun détourage partiel ne sera présenté comme accepté.',
    runtime: 'Conteneur',
    gpu: 'Mode',
    models: 'Modèles',
    refresh: 'Actualiser',
  },
  categories: [
    ['skincare', 'Soin de la peau'],
    ['makeup', 'Maquillage'],
    ['perfume', 'Parfum'],
    ['haircare', 'Soin des cheveux'],
    ['bodycare', 'Soin du corps'],
  ],
})

export const lockStatusLabel = (status) => ({
  needs_review: STUDIO_COPY.lock.statusReview,
  validated: STUDIO_COPY.lock.statusValidated,
  rejected: STUDIO_COPY.lock.statusRejected,
}[status] || STUDIO_COPY.lock.statusReview)
