export const STUDIO_COPY = Object.freeze({
  brand: 'Cosmetique AI',
  eyebrow: 'Atelier de campagne',
  title: 'Une image produit qui tient la route.',
  intro: 'Protégez le produit, donnez-lui un décor, puis gardez la main sur chaque détail.',
  privateWorkspace: 'Espace privé',
  campaignHistory: 'Historique des campagnes',
  source: {
    title: 'Commencez par le vrai produit',
    description: 'Importez une photo. Le produit original restera la référence de chaque rendu.',
    upload: 'Choisir une photo',
    change: 'Changer la photo',
    remove: 'Retirer la photo',
    stored: 'Source enregistrée',
    waiting: 'En attente de la source',
    ready: 'Prête à être enregistrée',
    name: 'Nom du produit',
    brand: 'Marque',
    optional: 'Facultatif',
    category: 'Catégorie',
    file: 'Fichier',
    storage: 'Stockage',
    privateStorage: 'Stockage privé',
    notStored: 'Pas encore enregistrée',
    createLock: 'Créer le Product Lock',
    refreshLock: 'Recalculer le Product Lock',
    creatingLock: 'Création du Product Lock',
    emptyTitle: 'Déposez une photo produit',
    emptyHelp: 'JPG, PNG ou WebP, 10 Mo maximum.',
    helper: 'La photo est enregistrée avant toute analyse.',
  },
  lock: {
    title: 'Vérifiez ce qui reste dans l’image',
    description: 'Le masque protège les pixels du produit pendant la création du décor.',
    statusReview: 'À vérifier',
    statusValidated: 'Validé',
    statusRejected: 'Refusé',
    candidate: 'Candidat',
    confidence: 'Confiance',
    revision: 'Révision',
    select: 'Sélectionner',
    positive: 'Garder',
    negative: 'Retirer',
    pan: 'Déplacer',
    mask: 'Afficher le masque',
    save: 'Enregistrer les corrections',
    saving: 'Enregistrement',
    validate: 'Valider le Product Lock',
    reject: 'Envoyer en revue',
    correctionReason: 'Motif de revue',
    correctionPlaceholder: 'Expliquez ce qui doit être vérifié.',
    evidence: 'Preuves du verrouillage',
    source: 'Source',
    maskArtifact: 'Masque',
    cutout: 'Détourage',
    models: 'Modèles',
    noArtifact: 'Non disponible',
    noCandidates: 'Aucun candidat supplémentaire n’est disponible.',
    reviewNote: 'Un contour ambigu, une main ou un objet supplémentaire doit être corrigé avant de continuer.',
  },
  direction: {
    title: 'Donnez une direction au décor',
    description: 'Choisissez une proposition automatique ou écrivez la scène que vous avez en tête.',
    automatic: 'Automatique',
    custom: 'Mon prompt',
    automaticHelp: 'Une direction française est préparée à partir du produit verrouillé et de sa catégorie.',
    customHelp: 'Décrivez la lumière, la matière et l’espace. Le produit reste protégé.',
    prompt: 'Prompt de décor',
    promptPlaceholder: 'Une table en pierre claire, lumière du matin, ombres douces, espace calme autour du produit.',
    audience: 'Usage prévu',
    audiencePlaceholder: 'Ex. lancement social, page produit',
    placement: 'Format',
    seed: 'Graine',
    preview: 'Préparer la direction',
    previewing: 'Préparation',
    generatedPreview: 'Direction préparée',
    guardrail: 'Protection du produit',
    guardrailText: 'Produit intact, sans main, sans personne, sans objet ajouté au premier plan.',
  },
  generation: {
    title: 'Rendez la scène',
    description: 'Colab reste le moteur principal et protège le produit avant chaque export.',
    engine: 'Moteur Colab',
    provider: 'Profil de rendu',
    noProvider: 'Aucun profil de rendu disponible',
    optional: '',
    variants: 'Variantes',
    budget: 'Plafond de coût',
    review: 'Revoir la demande',
    generate: 'Générer le décor',
    generating: 'Génération en cours',
    cancel: 'Annuler la demande',
    waiting: 'En attente du moteur',
    ready: 'Prête à générer',
    qa: 'Contrôle qualité',
    done: 'Prête à vérifier',
    failed: 'Génération interrompue',
    uncertain: 'Résultat à réconcilier',
  },
  review: {
    title: 'Vérifiez le rendu final',
    description: 'Le produit original est remis en place après le décor. Exportez uniquement une variante validée.',
    result: 'Résultat',
    original: 'Produit original',
    qaPassed: 'Contrôles validés',
    qaReview: 'Revue nécessaire',
    provenance: 'Provenance',
    model: 'Modèle',
    sourceHash: 'Empreinte source',
    outputHash: 'Empreinte résultat',
    cost: 'Coût',
    export: 'Télécharger le ZIP',
    exportBlocked: 'Export bloqué jusqu’à validation',
    empty: 'Aucune variante validée pour le moment.',
  },
  engine: {
    title: 'État du moteur',
    ready: 'Colab est prêt',
    unavailable: 'Colab est indisponible',
    degraded: 'Colab est en mode dégradé',
    checking: 'Vérification de Colab',
    unavailableHelp: 'Le studio attend un moteur GPU confirmé. Aucun résultat local ne sera inventé.',
    runtime: 'Runtime',
    gpu: 'GPU',
    models: 'Modèles chargés',
    refresh: 'Actualiser',
  },
  batch: {
    title: 'Traitement du dossier',
    description: 'Préparez le traitement des photos sans masquer les fichiers qui demandent une revue.',
    canonical: 'Photos sources',
    regression: 'Photos augmentées',
    acceptance: 'Cohorte de validation',
    create: 'Préparer le traitement',
    loading: 'Chargement du dossier',
    empty: 'Aucun traitement enregistré.',
    unavailable: 'Le suivi de dossier sera disponible avec le prochain backend.',
  },
  categories: [
    ['skincare', 'Soin de la peau'],
    ['makeup', 'Maquillage'],
    ['perfume', 'Parfum'],
    ['haircare', 'Soin des cheveux'],
    ['bodycare', 'Soin du corps'],
  ],
  placements: [
    ['square', 'Carré social'],
    ['portrait', 'Portrait social'],
    ['wide', 'Bannière large'],
  ],
})

export const lockStatusLabel = (status) => ({
  needs_review: STUDIO_COPY.lock.statusReview,
  validated: STUDIO_COPY.lock.statusValidated,
  rejected: STUDIO_COPY.lock.statusRejected,
}[status] || STUDIO_COPY.lock.statusReview)

export const generationStatusLabel = (status) => ({
  idle: STUDIO_COPY.generation.waiting,
  queued: STUDIO_COPY.generation.waiting,
  preparing: STUDIO_COPY.generation.waiting,
  waiting_provider: STUDIO_COPY.generation.waiting,
  rendering: STUDIO_COPY.generation.generating,
  qa: STUDIO_COPY.generation.qa,
  done: STUDIO_COPY.generation.done,
  failed: STUDIO_COPY.generation.failed,
  uncertain: STUDIO_COPY.generation.uncertain,
  canceled: 'Demande annulée',
}[status] || status || STUDIO_COPY.generation.waiting)
